site_name: Tilburg Science Hub
site_url: http://www.tilburgsciencehub.com
repo_url: https://github.com/tilburgsciencehub/tilburg-science-hub
edit_uri: https://github.com/tilburgsciencehub/tilburg-science-hub/blob/tilburg-update/docs/
repo_name: 'GitHub'
site_description: "Tilburg Science Hub is an open-source resource repository that supports students and researchers in the social sciences to set up reproducible workflows and to efficiently manage data- and computation-intensive projects."
site_author: Hannes Datta, Tobias J. Klein

nav:
- Home: index.md
- Project Setup and Workflow Management:
  - Getting Started: workflow/index.md
  - Pipelines and Project Components: workflow/pipeline.md
  - Data Management and Directory Structure: workflow/directories.md
  - Automating your Pipeline: workflow/automation.md
  - Documenting Code and Pipeline: workflow/documenting-code.md
  - Documenting Datasets: workflow/documenting-data.md
  - Versioning using Git/GitHub: workflow/versioning.md
  - Collaborating using GitHub: workflow/collaboration.md
    #- Overview:
    #- Workflow in make: workflow/automation_workflow.md
  #- Versioning: workflow/versioning.md
  #- Data storage: workflow/data.md
  #- Documentation: workflow/doc.md
  #- Housekeeping: workflow/housekeeping.md
  #- Portability: workflow/portability.md
  - Checklist to Audit your Project: workflow/checklist.md
- Software Setup:
  - Installation Guide Overview: setup/index.md
  #- Terminology: setup/terminology.md
  #- Command Line Tools: setup/commandLine.md
  - R: setup/r.md
  - Stata: setup/stata.md
  - Git: setup/gitInstall.md
  - Text Editor: setup/textEditor.md
#  - Perl: setup/perl.md
  - Python: setup/python.md
  - Python Packages: setup/python-packages.md
  - Build Tools/Make: setup/make.md
    # - Automation with Waf: setup/waf.md
    #- Automation with Snakemake: setup/snakemake.md
  - Webscraping: setup/webscraping_drivers.md
  - Teamviewer: setup/teamviewer.md
  - LaTeX: setup/latex.md
  - Add. Programming: setup/otherProgLang.md
#  - Pandoc: setup/pandoc.md
  # - Matlab: setup/matlab.md
  # - Path Settings: setup/path-setting.md
#- Manuals:
#  - How to write good code:
#  - Style instructions for papers:
#  - How to collaborate using Git @Hulai
#  -
- Project Templates and Tutorials:
    - Overview: examples/index.md
    - Tutorial:
        - Getting Started: tutorial/index.md
        - Verify Software Setup: tutorial/verify.md
        - Download the Template: tutorial/clone.md
        - Running the Workflow: tutorial/run.md
        - Inspecting the Data-preparation Pipeline: tutorial/pipeline-make.md
        - Dry-run of Make and First Modifications: tutorial/wipe-rerun.md
        - More Modifications: tutorial/modifications.md
        - Extending the Analysis: tutorial/analysis.md
        - Finished & Looking Ahead: tutorial/finish.md
- Tips and Manuals:
    - Learning R: tips/learn_R.md
    - Learning Python and Julia: tips/quantecon.md
    - Writing an Academic Paper: tips/paper.md
    - Writing Good Code: tips/coding.md
    - Setting up a file exchange: tips/fileexchanges.md
    - Links to other initatives: tips/links.md
- About: about.md
#- Acknowledgements: acknowledgement.md

theme:
  name: 'material'
  palette:
    #primary: 'Blue Grey' # default: indigo, other colors see https://squidfunk.github.io/mkdocs-material/getting-started/
    primary: 'indigo' # default: indigo, other colors see https://squidfunk.github.io/mkdocs-material/getting-started/
    accent: 'indigo'

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - attr_list

google_analytics: ['UA-23035208-2', 'tilburgsciencehub.com']
